apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.2.2
    helm:
      values: |
        alertmanager:
          enabled: true
          config:
            global:
              resolve_timeout: 5m
              smtp_from: 'alerts@mygitops.local'
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_auth_username: 'nahoangit@gmail.com'
              smtp_auth_password: 'rvzb myle vzrv dzzm'
            route:
              group_by: ['alertname']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 1h
              receiver: 'email-notifications'
            receivers:
            - name: 'email-notifications'
              email_configs:
              - to: 'nahoangit@gmail.com'
                send_resolved: true
        crds:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
